import Image from "next/image";
import Link from "next/link";

import { Badge } from "@/components/ui/badge";
import { buttonVariants } from "@/components/ui/button-variants";
import { Container } from "@/components/ui/container";
import { Section } from "@/components/ui/section";
import { SectionIndex } from "@/components/ui/section-index";
import { cn } from "@/lib/utils";

interface AlsoBuildingProps extends React.HTMLAttributes<HTMLElement> {
  /** 1-based position in the homepage sequence — the numbered eyebrow. */
  index: number;
  /** Stable selector for E2E tests; consumer provides — no default. */
  "data-testid"?: string;
}

/**
 * The next product, before it ships.
 *
 * Deliberately NOT on /npm: that page is a metrics surface scoped to the
 * ESLint plugins, and a row reading "0 downloads" markets nothing. The
 * homepage is where the site argues for the work, so a pre-release product
 * belongs here — the ask is a GitHub star now, which is the only signal a
 * package can earn before its first install.
 *
 * The mark is `burgee-flag.svg` (from the burgee repo's brand-assets, which
 * are generated by its `npm run brand`). The flag is used rather than either
 * lockup because the lockups bake in their own background rect — dark or
 * light — which would sit as a coloured block inside this card in one of the
 * two themes. The flag is transparent and reads on both.
 */
export function AlsoBuilding({
  index,
  className,
  "data-testid": testId,
  ...rest
}: AlsoBuildingProps) {
  return (
    <Section
      data-slot="landing-also-building"
      data-testid={testId}
      divider="bottom"
      spacing="tight"
      className={cn(className)}
      {...rest}
    >
      <Container size="content">
        <SectionIndex value={index} data-testid="also-building-index" className="mb-3">
          Also building
        </SectionIndex>
        <div className="rounded-xl border border-border bg-card p-8 shadow-sm sm:p-10">
          <div className="flex flex-col items-start gap-6 sm:flex-row sm:items-center">
            <Image
              src="/burgee-flag.svg"
              alt=""
              width={72}
              height={72}
              className="size-16 shrink-0 rounded-lg sm:size-20"
            />
            <div>
              <div className="flex flex-wrap items-center gap-3">
                <h2 className="font-mono text-2xl font-semibold tracking-tight sm:text-3xl">
                  burgee
                </h2>
                <Badge variant="secondary">Coming soon</Badge>
              </div>
              <p className="mt-1 text-sm text-muted-foreground">
                An agent-native CLI framework
              </p>
            </div>
          </div>

          <p className="mt-6 max-w-2xl text-muted-foreground">
            Drop-in compatible with commander and yargs, so an existing CLI
            keeps working. Declare a command once and{" "}
            <code className="font-mono text-sm">help</code>,{" "}
            <code className="font-mono text-sm">--json</code>,{" "}
            <code className="font-mono text-sm">--schema</code>,{" "}
            <code className="font-mono text-sm">--mcp</code> and shell
            completions are all projected from that single declaration — so the
            CLI a human reads is the same one an agent can call, without a
            second interface to keep in sync.
          </p>

          {/* buttonVariants sets `whitespace-nowrap`, so at 320px with text at
              200% these labels cannot wrap and push the document sideways —
              a WCAG 1.4.10 reflow failure the layout audit catches. Allowing
              the label to wrap inside a width-bounded button fixes it without
              shortening the copy or special-casing a breakpoint. */}
          <div className="mt-8 flex flex-wrap gap-3">
            <Link
              href="https://github.com/ofri-peretz/burgee"
              className={cn(
                buttonVariants({ variant: "default" }),
                "h-auto max-w-full whitespace-normal text-center",
              )}
            >
              ★ Star on GitHub
            </Link>
          </div>
        </div>
      </Container>
    </Section>
  );
}
